######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 11 15:12:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main_widget.cpp
