######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 10 16:26:46 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += slider.cpp
