######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 10 15:37:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
