######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 11 17:18:13 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_class.cpp
