######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 10 14:50:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello_qt.cpp
