######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 13 16:52:41 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += menubar.cpp
